### ISSUE TITLE
same ApI from Block.io in Bitez

### ISSUE THREAD

**Issue by mclauncherlinux** [merwane/Bitez#3]
could you add the same features and the same api from block.io in this wallet?

**Comment by merwane** [comment]
The goal of Bitez is to get rid of services such as Block.io by providing a self-hosted, open-source and free alternative. So what do you mean exactly?

**Comment by mclauncherlinux** [comment]
I just want have the same api ?

**Comment by merwane** [comment]
I don't want to make a copycat, this is simply an alternative.
