### ISSUE TITLE
can I use this to generate deposit addresses ?

### ISSUE THREAD

**Issue by mclauncherlinux** [merwane/Bitez#4]
can I use this for deposits on sites?

**Comment by merwane** [comment]
Of course, you can.

**Comment by mclauncherlinux** [comment]
ok i have currently coinpayments implemented, do you think a switch will be hard?

**Comment by merwane** [comment]
I'm trying to make Bitez integration as simple and seamless as possible. If you're facing any issue implementing it, feel free to contact me.

**Comment by mclauncherlinux** [comment]
https://www.coinpayments.net/apidoc-get-callback-address I use this

**Comment by merwane** [comment]
It's up to you to switch or not. I suggest you to explore Bitez before making any decision.

**Comment by mclauncherlinux** [comment]
do you have callbacks implemented?

**Comment by merwane** [comment]
Not yet
