### ISSUE TITLE
مشروع مميز وأتمني أن يتم تحديثه

### ISSUE THREAD

**Issue by abokareem** [merwane/Bitez#6]
تحياتى لك صديقى
بما أنك تتحدث العربية 
فأنا أكتب لك حاليا بلغتنا الام 
أحييك تحية كبيرة على مشاريعك المميزة
ولك مني كل الحب والتقدير أخي مروان
اريد التواصل معاك بطريقة أخري

**Comment by merwane** [comment]
!شكرا جزيلا على التشجيع
يمكنك الاتصال بي عن طريق البريد الإلكتروني على العنوان التالي
**contact@merwane.me**
